# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s1=s.split()
s1

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
p=np.zeros(10)
p

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
k=np.array([5]*10)
k

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
g=np.arange(20,35,2)
g

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
k=np.arange(0,9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
s=pd.DataFrame({'Name':['kow','sri','chan'],'Age':[20,21,21]})
s

   Name  Age
0   kow   20
1   sri   21
2  chan   21

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
k=pd.date_range(start='1-01-2023',end='10-02-2023',freq='d')
k

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
s=pd.DataFrame.from_records(lists)
s

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24